# Generated by Django 3.0.1 on 2019-12-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_item_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='', height_field=295.45, upload_to='', width_field=255),
        ),
    ]
