# Generated by Django 3.0.5 on 2020-04-19 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_item_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to=''),
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SP', 'Sports'), ('W', 'Winter'), ('P', 'Party Wear'), ('F', 'Formals'), ('C', 'Casuals'), ('B', 'Bikini')], max_length=2),
        ),
    ]
