# Generated by Django 3.0.5 on 2020-04-19 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200419_0631'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='previous_price',
        ),
        migrations.AddField(
            model_name='item',
            name='discount_price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
