# Generated by Django 3.0.5 on 2020-04-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200419_0643'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bestseller',
            field=models.BooleanField(default=False),
        ),
    ]
