# Generated by Django 3.0.5 on 2020-04-19 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_item_bestseller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='isNewItem',
            field=models.BooleanField(default=True),
        ),
    ]
